# Generated by Django 5.2.6 on 2025-09-13 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True)),
                ('chunk_size', models.IntegerField(blank=True)),
                ('last_solved_chunk', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.IntegerField(default=0)),
                ('text', models.TextField(blank=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('confidence_score', models.FloatField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('feedback', models.TextField(blank=True)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verification.solution')),
            ],
        ),
    ]
