# Generated by Django 5.2.6 on 2025-09-16 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='last_solved_chunk',
            new_name='cur_chunk',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='chunk_size',
        ),
    ]
